# Configurações do Google Cloud Platform (GCP)
GCP_PROJECT_ID = "python-468018"
BIGQUERY_DATASET = "aulapython"
BIGQUERY_TABLE_NAME = "sales"

BIGQUERY_TABLE_ID = f"{GCP_PROJECT_ID}.{BIGQUERY_DATASET}.{BIGQUERY_TABLE_NAME}"